In [6]:
import numpy as np

In [7]:
#inputs
x = np.array([[1,-1,-1,-1], [1,1,-1,-1], [-1,-1,-1,1],[-1,-1,1,1]])

#targets
t = np.array([[-1,1],[-1,1],[1,-1],[1,-1]])

In [8]:
print(x)

[[ 1 -1 -1 -1]
 [ 1  1 -1 -1]
 [-1 -1 -1  1]
 [-1 -1  1  1]]


In [9]:
sum = 0

In [10]:
for i in range(4):
    #converting to each row to matrix of x and transpose it
    w = np.transpose(np.matrix(x[i]))
    
    #multiply the target to the inputs
    result = np.multiply(w,t[i])
    
    #adding the all results of the target and inputs multiply 
    sum += result
print(sum)

[[-4  4]
 [-2  2]
 [ 2 -2]
 [ 4 -4]]


In [13]:
#testing the model
n = np.array([[1,1,0,0]])

In [14]:
#multiply by the sum
r = np.dot(n,sum)
r

matrix([[-6,  6]])

In [16]:
#if greater than 0 than 1 else -1
for i in range(2):
    if r[0,i] > 0:
        r[0,i] = 1
    elif r[0,i] == 0:
        r[0,i] = 0
    else:
        r[0,i] = -1

In [18]:
r

matrix([[-1,  1]])

In [19]:
#empty list
li = []

#array of the testing data 0 converted to -1
#n = np.array([[1,1,-1,-1]])

#hamming_dist list
hamming_dist = []

#calculation of the XOR for hamming dist
for i in range(4):
    if (t[i][0] == r[0,0]) and (t[i][1] == r[0,1]):
        for j in range(4):
            if x[i][j] == n[0][j]:
                li.append(-1)
            else:
                li.append(1)
                
        #counting number of 1's 
        count = 0
        for k in li:
            if k == 1:
                count += 1
                
        #converting x[i] to list for appending propose for getting the result
        w = x[i].tolist()
        w.append(count)
        hamming_dist.append(w)
        #empty the list again
        li = []
        
#finding the minimum value distance of the matched pattern
min_value = hamming_dist[0][-1]
for i in range(len(hamming_dist)):
    if min_value > hamming_dist[i][-1]:
        min_value = hamming_dist[i][-1]
        
#printing the final result of the hetro associative network
for i in hamming_dist:
    if min_value == i[-1]:
        print(i[0:len(i)-1])

[1, 1, -1, -1]


In [20]:
hamming_dist

[[1, -1, -1, -1, 3], [1, 1, -1, -1, 2]]